# Workflow manually triggered to push fork to upstream
name: Push to upstream

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'PR from Fork (URL)'
        default: ''
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: push-upstream
      run: |
        eval "$(ssh-agent -s)"
        DECODED_SSH_DEPLOY_KEY=$(echo ${{ GH_ACTION_SSH_KEY }} | base64 -d)
        ssh-add - \<<< "${DECODED_SSH_DEPLOY_KEY}"
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        git config --global user.name "Github Action"
        git config --global user.email "gh-action+bigquery-etl@mozilla.com"

        mkdir bin
        GPF_INSTALL_LOCATION=bin/git-push-fork-to-upstream-branch
        GPF_URL=https://raw.githubusercontent.com/jklukas/git-push-fork-to-upstream-branch/master/git-push-fork-to-upstream-branch
        sudo curl -sL $GPF_URL > $GPF_INSTALL_LOCATION
        chmod 755 $GPF_INSTALL_LOCATION
        export GPF_USE_SSH=true

        git clone git@github.com:scholtzan/gh-actions-test.git
        cd gh-actions-test

        ../bin/git-push-fork-to-upstream-branch git@github.com:scholtzan/gh-actions-test.git ${{ github.event.inputs.name }}
